spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://config-server:8071/"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://127.0.0.1:7080/realms/master/protocol/openid-connect/certs"
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s